### ISSUE TITLE
Port to Odin sandboxed SDK

### ISSUE THREAD

**Issue by hanaral** [phase1geo/Outliner#74]
I presume you could quite easily write a flatpak manifest that uses the odin SDK (which is now fully funcitonal and available for installing with `flatpak remote-add --if-not-exists elementary https://flatpak.elementary.io/elementary.flatpakrepo`
I'll see if I can make one myself and add it here

**Comment by hanaral** [comment]
This is the current YAML manifest I'm using:
```
app-id: com.github.phase1geo.outliner
runtime: io.elementary.Platform
runtime-version: 'daily' #change this to release version (currently 0.1.0) once they fix the lack of inherited GL extensions bug
sdk: io.elementary.Sdk
command: builder-test
finish-args:
  - '--filesystem=host'

  - '--socket=fallback-x11'
  - '--socket=wayland'
  - '--filesystem=xdg-run/dconf'
  - '--talk-name=org.gnome.SettingsDaemon'
  - '--talk-name=ca.desrt.dconf'
  - '--env=DCONF_USER_CONFIG_DIR=.config/dconf'
cleanup:
  - '/include'
  - '/lib/pkgconfig'
  - '/man'
  - '/share/gtk-doc'
  - '/share/man'
  - '/share/pkgconfig'
  - '/share/vala'
  - '*.a'
  - '*.la'
modules:

  - name: discount
    buildsystem: simple
    cleanup:
        '*.a'

    build-commands:
      - ./configure.sh --prefix=/app --enable-all-features --github-checkbox --with-fenced-code --shared
      - sed -e 's|/sbin/ldconfig|/sbin/ldconfig -n|' -i librarian.sh
      - make install

    sources:
      - type: archive
        url: http://www.pell.portland.or.us/~orc/Code/discount/discount-2.2.6.tar.bz2
        sha256: ae68a4832ff8e620286304ec525c1fe8957be4d8f1e774588eb03d1c3deb74a7

  - name: Outliner
    buildsystem: meson
    config-opts:
     - '--libdir=lib'
    sources:
      - type: dir
        path: .
```

It runs fine until the `appstrea-compose` part, at which point it fails with the error:
```
Running appstream-compose
Processing application com.github.phase1geo.outliner
Error loading AppData file: failed to parse /app/share/appdata/com.github.phase1geo.outliner.appdata.xml: Error on line 284 char 119: <li> already set 'Added new' and tried to replace with ' keyboard shortcut for positioning currently selected row at the top of the window.'
```
